{ pkgs, pkgs-unstable }:

# programming languages and tooling
with pkgs;
[
  air
  astro-language-server
  bash-language-server
  biome
  black
  pkgs-unstable.bun
  clang-tools
  cling
  emmet-language-server
  erlang
  eslint_d
  flutter
  gcc14
  gdb
  gdtoolkit_4
  # pkgs-unstable.gleam
  go
  golangci-lint
  google-java-format
  gopls
  haskell.compiler.ghc9103
  haskellPackages.cabal-gild
  haskellPackages.cabal-install
  haskellPackages.ghcid
  haskellPackages.haskell-language-server
  haskellPackages.hlint
  haskellPackages.ormolu
  isort
  jdk25
  jdt-language-server
  lua
  lua-language-server
  nil
  nixfmt-rfc-style
  nodejs
  odin
  ols
  prettier
  prettierd
  pkgs-unstable.pyrefly
  python3
  python312Packages.pip
  rustup
  stylua
  stylish-haskell
  svelte-language-server
  tailwindcss-language-server
  tinymist
  typescript-language-server
  typst
  typstyle
  vscode-langservers-extracted
  yaml-language-server
]
